# Custom Language File for Launcher Customizer

[ejs.app]
title = "SongLim : Crime Day"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "송림에 입주하신 여러분, 환영합니다."
welcomeDescription = "송림은 평화롭고 조용한 도시처럼 보이지만, 그 이면에서는 무법자들과 경찰 간의 긴장이 끊이지 않습니다. 도시 곳곳에서 벌어지는 다양한 사건들은 송림의 어두운 면을 드러내기도 하나, 동시에 이곳은 수많은 사람들이 삶을 꾸려가는 활기가 가득한 도시이기도 합니다. 농부, 어부, 광부, 요리사 등 다양한 직업이 존재하며, 각자의 방식으로 도시를 지탱하고 있죠. 어떤 삶을 선택하든, 이곳 송림에서는 누구나 자신만의 이야기를 써 내려갈 수 있습니다. 하지만 주의하세요. 이 도시는 겉모습만 보고 판단할 수 없으니까요."
welcomeDescCTA = "앞으로 송림을 마주하기까지, 단 몇걸음 남지 않았습니다."
